# Generates anchor/golden_test.go: canonical_claim_bytes of a claim built to hit every
# divergence Anchor Format v1 section 0 lists, computed by the reference expression that
# section 1 gives ("In Python this is exactly"). Run from the repository root:
#   python3 anchor/testdata/golden.py > anchor/golden_test.go && gofmt -w anchor/golden_test.go
# Every non-ASCII and escape character is built with chr(), so no escape sequence passes
# through a text editor.
import hashlib
import json

claim = {
    "eat_profile": "tag:agentrust-io.com,2026:trace-v0.2",
    "bmp": "caf" + chr(0xE9) + " " + chr(0x20AC) + "5",
    "astral": "smile " + chr(0x1F600),
    "controls": chr(0x7F) + chr(0x01) + chr(0x1F) + "\t\n\r\b\f" + chr(0x22) + chr(0x5C) + "/",
    # Key order: code point puts U+FFFF before U+1F600; UTF-16 code units put it after.
    chr(0xFFFF): "last BMP code point as a key",
    chr(0x1F600): "astral key",
    "ints": [0, -1, 9007199254740991, -9007199254740991],
    "nested": {"b": [True, False, None], "a": {}},
}

source = json.dumps(claim, ensure_ascii=False, separators=(", ", ": ")).encode("utf-8")
canonical = json.dumps(claim, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("ascii")
leaf = "sha256:" + hashlib.sha256(b"\x00" + canonical).hexdigest()

assert b"`" not in canonical
print("// Code generated by anchor/testdata/golden.py; DO NOT EDIT.")
print()
print("package anchor")
print()
print("// goldenSource is the claim as UTF-8 JSON, hex-encoded so this file stays ASCII.")
print('const goldenSource = "' + source.hex() + '"')
print()
print("// goldenCanonical is section 1's reference expression over goldenSource.")
print("const goldenCanonical = `" + canonical.decode("ascii") + "`")
print()
print('const goldenLeaf = "' + leaf + '"')
